# Generated by Django 3.2.14 on 2022-09-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220903_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='password',
            new_name='token',
        ),
    ]
