# Generated by Django 3.2.14 on 2022-09-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_password_restaurant_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='lastchange',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='token',
        ),
    ]
