# Generated by Django 3.2.14 on 2022-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220903_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='voted',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
