# Generated by Django 3.2.14 on 2022-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_restaurant_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='disliked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
